try{
    console.log('try block first statement');
    //let a=(5/0);
    //booo();
    //console.log(x);
    x=2;
    arr=[1,2];
    //console.log(arr[x]);
    //Number.MAX_VALUE
}
catch(exception){
    console.log(exception.message);
}